# Generated by Django 2.2 on 2019-12-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='legend',
            field=models.BooleanField(default=False),
        ),
    ]
