# Generated by Django 2.2 on 2019-12-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_plot_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquery',
            name='end_date_select',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectquery',
            name='start_date_select',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
