# Generated by Django 2.2 on 2019-12-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20191223_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('plot_type', models.CharField(blank=True, choices=[('Scatter', 'Scatter'), ('Bar', 'Bar'), ('Line', 'Line'), ('Histogram', 'Histogram')], max_length=20, null=True)),
                ('x_axis', models.CharField(blank=True, max_length=200, null=True)),
                ('y_axis', models.CharField(blank=True, max_length=200, null=True)),
                ('z_axis', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('legend', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ProjectQuery')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectdashboard',
            name='endp_point',
            field=models.ManyToManyField(blank=True, null=True, related_name='dashboard_users', to='coreapp.ProjectEndPoint'),
        ),
    ]
