# Generated by Django 2.2 on 2019-12-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20191227_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdashboard',
            old_name='endp_point',
            new_name='end_point',
        ),
    ]
