# Generated by Django 2.2 on 2019-12-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_auto_20191227_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttype',
            name='expected_ans',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='type',
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_type',
            field=models.CharField(choices=[('scatter_2d', 'scatter_2d'), ('scatter_3d', 'scatter_3d'), ('bar', 'bar'), ('line_2d', 'line_2d'), ('line_3d', 'line_3d'), ('histogram', 'histogram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdashboard',
            name='end_point',
            field=models.ManyToManyField(related_name='dashboard_users', to='coreapp.ProjectEndPoint'),
        ),
        migrations.AlterField(
            model_name='projectendpoint',
            name='plot_type',
            field=models.CharField(blank=True, choices=[('scatter_2d', 'scatter_2d'), ('scatter_3d', 'scatter_3d'), ('bar', 'bar'), ('line_2d', 'line_2d'), ('line_3d', 'line_3d'), ('histogram', 'histogram')], max_length=20, null=True),
        ),
    ]
