# Generated by Django 2.2 on 2020-01-20 12:49

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_projectdashboard_dashboard_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='')),
                ('file_1_header', models.BooleanField(default=True)),
                ('file_2_header', models.BooleanField(default=True)),
                ('file_3_header', models.BooleanField(default=True)),
                ('file_1_delimiter', models.CharField(blank=True, max_length=2, null=True)),
                ('file_2_delimiter', models.CharField(blank=True, max_length=2, null=True)),
                ('file_3_delimiter', models.CharField(blank=True, max_length=2, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFileRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('relation', jsonfield.fields.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
