# Generated by Django 2.2 on 2020-01-25 07:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_projectfilerelationship_projecttemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='date_format',
        ),
        migrations.AddField(
            model_name='projectfilerelationship',
            name='relation_mapping',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='projectjsonstorage',
            name='columns',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ProjectScheema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('schema', jsonfield.fields.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
