# Generated by Django 2.2 on 2020-01-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_auto_20200125_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectScheema',
            new_name='ProjectSchema',
        ),
    ]
