# Generated by Django 2.2 on 2020-01-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_auto_20200128_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquery',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectquery',
            name='legend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectquery',
            name='plot_type',
            field=models.CharField(blank=True, choices=[('scatter_2d', 'scatter_2d'), ('scatter_3d', 'scatter_3d'), ('bar', 'bar'), ('line_2d', 'line_2d'), ('line_3d', 'line_3d'), ('histogram', 'histogram')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectquery',
            name='x_axis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectquery',
            name='y_axis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectquery',
            name='z_axis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
