# Generated by Django 2.2 on 2020-01-30 13:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_auto_20200129_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectendpoint',
            name='alignment_object',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
