# Generated by Django 2.2 on 2020-02-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_auto_20200203_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrychoices',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='industrychoices',
            name='Industry_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='data_description',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='data_title',
        ),
        migrations.AddField(
            model_name='industrychoices',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='industrychoices',
            name='description',
            field=models.TextField(blank=True, default='some text...', null=True),
        ),
        migrations.AddField(
            model_name='industrychoices',
            name='name',
            field=models.CharField(blank=True, default='Unknown...', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='industrychoices',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date'),
        ),
        migrations.AddField(
            model_name='industrychoices',
            name='version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_goal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
