# Generated by Django 2.2 on 2020-02-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_auto_20200203_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
