# Generated by Django 2.2 on 2020-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_auto_20200203_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_goal',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
