# Generated by Django 2.2 on 2020-02-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_auto_20200205_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdashboard',
            name='dashboard_for',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Dashboard Users', 'Dashboard Users')], default='Public', max_length=30),
            preserve_default=False,
        ),
    ]
