# Generated by Django 2.2 on 2020-02-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_projectdashboard_dashboard_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdashboard',
            name='hash_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
