# Generated by Django 2.2 on 2020-02-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0023_projectdashboard_hash_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardAlgorithm',
            new_name='EndPointAlgorithm',
        ),
        migrations.AlterField(
            model_name='projectdashboard',
            name='dashboard_for',
            field=models.CharField(choices=[('Public', 'Public'), ('Me Only', 'Me Only'), ('Dashboard Users', 'Dashboard Users')], max_length=30),
        ),
    ]
