# Generated by Django 2.2 on 2020-02-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_auto_20200211_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointalgorithm',
            name='query',
        ),
        migrations.AddField(
            model_name='endpointalgorithm',
            name='end_point',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='coreapp.ProjectEndPoint'),
            preserve_default=False,
        ),
    ]
