# Generated by Django 2.2 on 2020-02-13 17:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0027_dataframedisplay_df'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJsonStorageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('rows', models.PositiveIntegerField()),
                ('columns', models.PositiveIntegerField()),
                ('head_json', jsonfield.fields.JSONField(default=dict)),
                ('tail_json', jsonfield.fields.JSONField(default=dict)),
                ('project_json', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ProjectJsonStorage')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
