# Generated by Django 2.2 on 2020-02-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0028_projectjsonstoragemetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='project_user',
        ),
    ]
