# Generated by Django 2.2 on 2020-02-15 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreapp', '0029_remove_projectuser_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='permission',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='project_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
