# Generated by Django 2.2 on 2020-02-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0030_auto_20200215_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
