# Generated by Django 2.2 on 2020-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0031_projectuser_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
