# Generated by Django 2.2 on 2020-03-10 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0034_projectiqu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBillingPrms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('query_count', models.PositiveIntegerField(default=0)),
                ('admin', models.PositiveIntegerField(default=1)),
                ('user', models.PositiveIntegerField(default=5)),
                ('end_point', models.PositiveIntegerField(default=5)),
                ('dahboard', models.PositiveIntegerField(default=5)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProjectIQU',
        ),
    ]
