# Generated by Django 2.2 on 2020-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0035_auto_20200310_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbillingprms',
            name='admin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingprms',
            name='dahboard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingprms',
            name='end_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingprms',
            name='user',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
