# Generated by Django 2.2 on 2020-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0036_auto_20200313_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdashboard',
            name='public_shared_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
