# Generated by Django 2.2 on 2020-03-17 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0038_auto_20200314_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdashboard',
            name='report_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
