# Generated by Django 2.2 on 2020-03-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0039_projectdashboard_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquery',
            name='aggregation_query',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='projectquery',
            name='group_query',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectquery',
            name='where_query',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
