# Generated by Django 2.2 on 2020-03-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0040_auto_20200317_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBillingMonthCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('admin_cost', models.PositiveIntegerField(default=0)),
                ('user_cost', models.PositiveIntegerField(default=0)),
                ('ens_point_cost', models.PositiveIntegerField(default=0)),
                ('dashboard_cost', models.PositiveIntegerField(default=0)),
                ('iqu_cost', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBillingHourlyCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('admin_cost', models.PositiveIntegerField(default=0)),
                ('user_cost', models.PositiveIntegerField(default=0)),
                ('end_point_cost', models.PositiveIntegerField(default=0)),
                ('dashboard_cost', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBillingDayCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('admin_cost', models.PositiveIntegerField(default=0)),
                ('user_cost', models.PositiveIntegerField(default=0)),
                ('ens_point_cost', models.PositiveIntegerField(default=0)),
                ('dashboard_cost', models.PositiveIntegerField(default=0)),
                ('iqu_cost', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
