# Generated by Django 2.2 on 2020-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0042_auto_20200324_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('user', models.PositiveIntegerField(default=0)),
                ('end_point', models.PositiveIntegerField(default=0)),
                ('iqs', models.PositiveIntegerField(default=0)),
                ('disk_space', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='projectbillingdaycost',
            old_name='admin_cost',
            new_name='disk_space_cost',
        ),
        migrations.RenameField(
            model_name='projectbillinghourlycost',
            old_name='admin_cost',
            new_name='disk_space_cost',
        ),
        migrations.RenameField(
            model_name='projectbillingmonthcost',
            old_name='admin_cost',
            new_name='disk_space_cost',
        ),
        migrations.RemoveField(
            model_name='projectbillingdaycost',
            name='dashboard_cost',
        ),
        migrations.RemoveField(
            model_name='projectbillinghourlycost',
            name='dashboard_cost',
        ),
        migrations.RemoveField(
            model_name='projectbillingmonthcost',
            name='dashboard_cost',
        ),
    ]
