# Generated by Django 2.2 on 2020-03-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0043_auto_20200326_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbillingprms',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='projectbillingprms',
            name='dahboard',
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='disk_space',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='end_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='iqs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='projectpricing',
            name='user',
            field=models.FloatField(default=0.0),
        ),
    ]
