# Generated by Django 2.2 on 2020-03-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0044_auto_20200327_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbillingdaycost',
            old_name='ens_point_cost',
            new_name='end_point_cost',
        ),
        migrations.RenameField(
            model_name='projectbillingmonthcost',
            old_name='ens_point_cost',
            new_name='end_point_cost',
        ),
    ]
