# Generated by Django 2.2 on 2020-03-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0045_auto_20200327_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbillingdaycost',
            old_name='iqu_cost',
            new_name='iqs_cost',
        ),
        migrations.RenameField(
            model_name='projectbillingmonthcost',
            old_name='iqu_cost',
            new_name='iqs_cost',
        ),
    ]
