# Generated by Django 2.2 on 2020-03-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0047_auto_20200329_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbillingdaycost',
            name='disk_space_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingdaycost',
            name='end_point_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingdaycost',
            name='iqs_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingdaycost',
            name='user_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillinghourlycost',
            name='disk_space_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillinghourlycost',
            name='end_point_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillinghourlycost',
            name='user_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingmonthcost',
            name='disk_space_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingmonthcost',
            name='end_point_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingmonthcost',
            name='iqs_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbillingmonthcost',
            name='user_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('invoice_id', models.CharField(max_length=10)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('bill_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=30)),
                ('monthly_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ProjectBillingMonthCost')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
