# Generated by Django 2.2 on 2020-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0052_tax_tax_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvoice',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
