# Generated by Django 2.2 on 2020-04-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0053_projectinvoice_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectendpoint',
            name='color',
        ),
        migrations.RemoveField(
            model_name='projectendpoint',
            name='legend',
        ),
        migrations.RemoveField(
            model_name='projectendpoint',
            name='plot_type',
        ),
        migrations.RemoveField(
            model_name='projectendpoint',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='projectendpoint',
            name='y_axis',
        ),
        migrations.RemoveField(
            model_name='projectendpoint',
            name='z_axis',
        ),
        migrations.RemoveField(
            model_name='projectquery',
            name='color',
        ),
        migrations.RemoveField(
            model_name='projectquery',
            name='legend',
        ),
        migrations.RemoveField(
            model_name='projectquery',
            name='plot_type',
        ),
        migrations.RemoveField(
            model_name='projectquery',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='projectquery',
            name='y_axis',
        ),
        migrations.RemoveField(
            model_name='projectquery',
            name='z_axis',
        ),
        migrations.AddField(
            model_name='plot',
            name='hover_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='orientation',
            field=models.CharField(blank=True, choices=[('h', 'Horizontal'), ('v', 'Vertical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='values',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectendpoint',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.Plot'),
        ),
        migrations.AddField(
            model_name='projectquery',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.Plot'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_type',
            field=models.CharField(choices=[('scatter_2d', 'scatter_2d'), ('scatter_3d', 'scatter_3d'), ('bar', 'bar'), ('line_2d', 'line_2d'), ('line_3d', 'line_3d'), ('histogram', 'histogram'), ('box_plot', 'box_plot'), ('time_series_plot', 'time_series_plot'), ('bubble_plot', 'bubble_plot'), ('heatmap', 'heatmap'), ('pie_chat', 'pie_chat')], max_length=20),
        ),
    ]
