# Generated by Django 2.2 on 2020-04-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0054_auto_20200413_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProjectPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('user', models.FloatField(default=0.0)),
                ('end_point', models.FloatField(default=0.0)),
                ('iqs', models.FloatField(default=0.0)),
                ('disk_space', models.FloatField(default=0.0)),
                ('free_tire', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectpricing',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_type',
            field=models.CharField(choices=[('scatter_2d', 'scatter_2d'), ('scatter_3d', 'scatter_3d'), ('bar', 'bar'), ('line_2d', 'line_2d'), ('line_3d', 'line_3d'), ('histogram', 'histogram'), ('box_plot', 'box_plot'), ('time_series_plot', 'time_series_plot'), ('bubble_plot', 'bubble_plot'), ('heatmap', 'heatmap'), ('pie_chart', 'pie_chat'), ('horizontal_bar', 'horizontal_bar')], max_length=20),
        ),
    ]
