# Generated by Django 2.2 on 2020-04-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0055_auto_20200418_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointalgorithm',
            name='prediction_column_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ApiDataGet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('api', models.CharField(max_length=1000)),
                ('basic_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('6 Months', '6 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
