# Generated by Django 2.2 on 2020-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0057_projectpricing_custom_supprt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpointalgorithm',
            old_name='algorithm',
            new_name='model_id',
        ),
        migrations.RemoveField(
            model_name='endpointalgorithm',
            name='prediction_column_name',
        ),
        migrations.AddField(
            model_name='endpointalgorithm',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointalgorithm',
            name='type_of_prediction',
            field=models.CharField(blank=True, choices=[('Classification', 'Classification'), ('Linear', 'Linear')], max_length=100, null=True),
        ),
    ]
