# Generated by Django 2.2 on 2020-04-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0058_auto_20200426_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndPointAlgorithm',
        ),
    ]
