# Generated by Django 2.2 on 2020-04-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0060_endpointalgorithm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointalgorithm',
            name='end_point',
        ),
        migrations.AddField(
            model_name='projectendpoint',
            name='algorithm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.EndPointAlgorithm'),
        ),
    ]
