# Generated by Django 2.2 on 2020-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0061_auto_20200426_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointalgorithm',
            name='accuracy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
