# Generated by Django 2.2 on 2020-04-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0062_auto_20200426_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointalgorithm',
            name='no_of_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
