# Generated by Django 2.2 on 2020-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0064_projectpricing_monthly_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultprojectpricing',
            name='monthly_maintenance',
            field=models.FloatField(default=39),
        ),
    ]
