# Generated by Django 2.2 on 2020-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0066_auto_20200505_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultprojectpricing',
            name='custom_supprt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projectbillingmonthcost',
            name='custom_supprt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projectbillingmonthcost',
            name='monthly_maintenance',
            field=models.FloatField(default=49),
        ),
    ]
