# Generated by Django 2.2 on 2020-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0068_plot_facet_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointalgorithm',
            name='model_size',
            field=models.FloatField(default=0.0),
        ),
    ]
