# Generated by Django 2.2 on 2020-05-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0069_endpointalgorithm_model_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbillingmonthcost',
            name='disk_space_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
