# Generated by Django 2.2 on 2020-05-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0070_projectbillingmonthcost_disk_space_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delete_obj',
            field=models.BooleanField(default=True),
        ),
    ]
