# Generated by Django 2.2 on 2020-07-28 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreapp', '0072_auto_20200611_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidataget',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('1Minute', '1 Minute'), ('5Minutes', '5 Minutes'), ('10Minutes', '10 Minutes'), ('15Minutes', '15 Minutes'), ('30Minutes', '30 Minutes'), ('1Hour', '1 Hour'), ('6Hours', '6 Hours'), ('12Hours', '12 Hours'), ('Weekly', 'Weekly'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('6 Months', '6 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Never', 'Never')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectdashboard',
            name='report_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('1Minute', '1 Minute'), ('5Minutes', '5 Minutes'), ('10Minutes', '10 Minutes'), ('15Minutes', '15 Minutes'), ('30Minutes', '30 Minutes'), ('1Hour', '1 Hour'), ('6Hours', '6 Hours'), ('12Hours', '12 Hours'), ('Weekly', 'Weekly'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('6 Months', '6 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Never', 'Never')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectendpoint',
            name='sub_df_frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('1Minute', '1 Minute'), ('5Minutes', '5 Minutes'), ('10Minutes', '10 Minutes'), ('15Minutes', '15 Minutes'), ('30Minutes', '30 Minutes'), ('1Hour', '1 Hour'), ('6Hours', '6 Hours'), ('12Hours', '12 Hours'), ('Weekly', 'Weekly'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('6 Months', '6 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Never', 'Never')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EndpointMlApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('api', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ProjectEndPoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
