# Generated by Django 2.2 on 2020-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0074_endpointmlapi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointmlapi',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PROCESSED', 'PROCESSED'), ('CANCELLED', 'CANCELLED')], default='OPEN', max_length=20),
        ),
    ]
