# Generated by Django 2.2 on 2020-08-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0075_auto_20200728_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPointNewColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('column_name', models.CharField(max_length=500)),
                ('formula', models.TextField()),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ProjectEndPoint')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
