# Generated by Django 2.2 on 2020-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0076_endpointnewcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfilename',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
