# Generated by Django 2.2 on 2019-12-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteseo',
            name='seo_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteseo',
            name='seo_keyword',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siteseo',
            name='seo_title',
            field=models.TextField(),
        ),
    ]
