# Generated by Django 2.2.7 on 2020-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketissue',
            old_name='image_1',
            new_name='client_image_1',
        ),
        migrations.RenameField(
            model_name='ticketissue',
            old_name='image_2',
            new_name='client_image_2',
        ),
        migrations.RenameField(
            model_name='ticketissue',
            old_name='image_3',
            new_name='client_image_3',
        ),
        migrations.RenameField(
            model_name='ticketissue',
            old_name='image_4',
            new_name='client_image_4',
        ),
        migrations.AddField(
            model_name='ticketissue',
            name='solution_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticketissue',
            name='solution_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticketissue',
            name='solution_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticketissue',
            name='solution_image_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticketissue',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Solved', 'Solved'), ('Tested', 'Tested'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
