# Generated by Django 2.2.7 on 2020-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdesk', '0002_auto_20200223_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketissue',
            name='image_1_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketissue',
            name='image_2_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketissue',
            name='image_3_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketissue',
            name='image_4_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low')], max_length=10),
        ),
    ]
