# Generated by Django 2.2.7 on 2020-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdesk', '0003_auto_20200225_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketissue',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
