# Generated by Django 2.2 on 2020-08-19 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0075_auto_20200728_2143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qdesk', '0007_ticketissue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='image_1_str',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='image_2_str',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='image_3_str',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='image_4_str',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='ticketissue',
            name='url',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], default='High', max_length=10),
        ),
    ]
