# Generated by Django 2.2 on 2020-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdesk', '0008_auto_20200819_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
