# Generated by Django 2.2 on 2019-12-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAPIDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('access_token', models.CharField(max_length=200)),
                ('integration_choice', models.CharField(choices=[('Google Drive', 'Google Drive'), ('Google Sheets', 'Google Sheets'), ('OneDrive', 'OneDrive'), ('Segment', 'Segment'), ('DropBox', 'DropBox')], max_length=200)),
                ('credentials', models.FileField(upload_to='credentials_file')),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('client_secret_key', models.CharField(max_length=200, null=True)),
                ('range', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('6 Months', '6 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='', max_length=200)),
                ('token_file', models.CharField(max_length=1000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Project')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
