# Generated by Django 2.2 on 2020-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapidetails',
            name='api',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerapidetails',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customerapidetails',
            name='integration_choice',
            field=models.CharField(choices=[('Google Drive', 'Google Drive'), ('Google Sheets', 'Google Sheets'), ('OneDrive', 'OneDrive'), ('Segment', 'Segment'), ('DropBox', 'DropBox'), ('API', 'API')], max_length=200),
        ),
    ]
