# Generated by Django 2.2 on 2020-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0002_auto_20200611_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapidetails',
            name='range',
            field=models.CharField(choices=[('Daily', 'Daily'), ('1Minute', '1 Minute'), ('5Minutes', '5 Minutes'), ('10Minutes', '10 Minutes'), ('15Minutes', '15 Minutes'), ('30Minutes', '30 Minutes'), ('1Hour', '1 Hour'), ('6Hours', '6 Hours'), ('12Hours', '12 Hours'), ('Weekly', 'Weekly'), ('15 Days', '15 Days'), ('1 Month', '1 Month'), ('6 Months', '6 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly'), ('Never', 'Never')], default='', max_length=200),
        ),
    ]
