# Generated by Django 2.2 on 2020-08-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0004_customerapidetails_sheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapidetails',
            name='sheet_header',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
