# Generated by Django 2.2 on 2019-12-19 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown...', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='some text...', null=True)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('contact_no', models.CharField(max_length=10, null=True, unique=True)),
                ('address_1', models.CharField(blank=True, max_length=300, null=True)),
                ('zipcode', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('industry', models.CharField(choices=[('Industry type', 'Industry type'), ('Health Care', 'Health Care'), ('Travel', 'Travel'), ('Education', 'Education'), ('Aerospace ', 'Aerospace '), ('Automobile ', 'Automobile '), ('Banking', 'Banking'), ('Ecommerce ', 'Ecommerce '), ('Financial Services ', 'Financial Services '), ('FMCG ', 'FMCG '), ('Gems and Jewellery ', 'Gems and Jewellery '), ('Insurance ', 'Insurance '), ('IT and ITES ', 'IT and ITES '), ('Manufacturing ', 'Manufacturing '), ('Metals and Mining ', 'Metals and Mining '), ('Oil and Gas ', 'Oil and Gas '), ('Power ', 'Power '), ('Railways ', 'Railways '), ('Real Estate', 'Real Estate'), ('Agriculture and Allied Industries', 'Agriculture and Allied Industries'), ('Construction', 'Construction'), ('Pharmaceutical ', 'Pharmaceutical '), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('News Media ', 'News Media '), ('Music', 'Music'), ('Renewable Energy', 'Renewable Energy'), ('Retail', 'Retail'), ('Roads', 'Roads'), ('Science and Technology', 'Science and Technology'), ('Textile', 'Textile'), ('Tourism and Hospitality', 'Tourism and Hospitality'), ('Marketing ', 'Marketing ')], max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('company_address_1', models.CharField(max_length=50, null=True)),
                ('employee_strength', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
