# Generated by Django 2.2 on 2020-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(choices=[('', ''), ('Health Care', 'Health Care'), ('Travel', 'Travel'), ('Education', 'Education'), ('Aerospace ', 'Aerospace '), ('Automobile ', 'Automobile '), ('Banking', 'Banking'), ('Ecommerce ', 'Ecommerce '), ('Financial Services ', 'Financial Services '), ('FMCG ', 'FMCG '), ('Gems and Jewellery ', 'Gems and Jewellery '), ('Insurance ', 'Insurance '), ('IT and ITES ', 'IT and ITES '), ('Manufacturing ', 'Manufacturing '), ('Metals and Mining ', 'Metals and Mining '), ('Oil and Gas ', 'Oil and Gas '), ('Power ', 'Power '), ('Railways ', 'Railways '), ('Real Estate', 'Real Estate'), ('Agriculture and Allied Industries', 'Agriculture and Allied Industries'), ('Construction', 'Construction'), ('Pharmaceutical ', 'Pharmaceutical '), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('News Media ', 'News Media '), ('Music', 'Music'), ('Renewable Energy', 'Renewable Energy'), ('Retail', 'Retail'), ('Roads', 'Roads'), ('Science and Technology', 'Science and Technology'), ('Textile', 'Textile'), ('Tourism and Hospitality', 'Tourism and Hospitality'), ('Marketing ', 'Marketing ')], max_length=50, null=True),
        ),
    ]
