# Generated by Django 2.2 on 2020-03-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customer_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
