# Generated by Django 2.2 on 2020-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200324_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat_gst_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
