# Generated by Django 2.2 on 2020-08-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_customer_vat_gst_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Company', 'Company')], max_length=50),
        ),
    ]
